# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktracker', '0002_auto_20160528_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
