# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktracker', '0003_auto_20160613_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='bloom_ticker',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
