# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktracker', '0005_auto_20160620_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, default='-', max_length=10),
        ),
    ]
