# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktracker', '0006_stock_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ebitda',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='open',
        ),
        migrations.AddField(
            model_name='stock',
            name='revenue',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='get_high',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='get_low',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pb_ratio',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
    ]
